name: CI for Fibo2

on:
  push:
    branches: [ Fibonacci ]
  pull_request:
    branches: [ Fibonacci ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar el codigo
      uses: actions/checkout@v3

    - name: Instalar JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Descargar JUnit y AssertJ JARs
      run: |
        wget https://search.maven.org/remotecontent?filepath=junit/junit/4.13.2/junit-4.13.2.jar -O junit.jar
        wget https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar -O hamcrest.jar
        wget https://search.maven.org/remotecontent?filepath=org/assertj/assertj-core/3.22.0/assertj-core-3.22.0.jar -O assertj-core.jar

  


